## datasource
spring:
  datasource:
    name: mysql
    url: jdbc:mysql://47.106.112.192:3306/finch_god?characterEncoding=utf-8&useSSL=false
    username: root
    password: alliance
    driverClassName: com.mysql.jdbc.Driver
    minIdle: 3
    maxActive: 40
    initialSize: 3
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    type: com.alibaba.druid.pool.DruidDataSource

csrf:
  types: token    # 验证方式(referer/token)(多种使用";"分隔)
  referers: http://47.106.112.192   # referer验证方式下的url(多种使用";"分隔，使用token方式可以不配置)
  paramName: p_token    # token验证方式下的token参数名
  tokenName: c_token    # token验证方式下的cookie名
  tokenUrl: /token    # token验证方式下的token生成地址
  tokenMaxAge: 7200    # token验证方式下的cookie有效期(单位:s)

